// The hand-back report of one cycle, as Markdown: what it credited and why, what it did not earn, the drift it
// caught, the proof that the history adds up, and what runs next. Pure; the screen copies it or posts it as an issue.
import type { CyclesData } from '../build';
import { replay, rungLabel, summarize, total } from '../replay';
import type { Cycle, CycleChange } from '../types';
import { VERDICT_WORD } from '../words';

const sign = (n: number): string => (n > 0 ? `+${n}` : String(n));
const ref = (c: CycleChange): string => c.mr ?? c.gap ?? c.kind;
const row = (c: CycleChange): string => `| ${ref(c)} | ${c.stage} | ${rungLabel(c.from)} → R${c.to} | ${VERDICT_WORD[c.verdict]} | ${c.why.replace(/\|/g, '/')} |`;

/** The issue title a report is posted under. */
export const reportTitle = (c: Cycle, project: string): string => `Afterlife ${c.id} · ${c.theme} · ${project}`;

/**
 * The report for a closed cycle. Every number in it is re-derived here from the same model the screen draws, and the
 * two proofs (replay = scan, chain holds) are stated as they stand, never assumed.
 */
export function cycleReport(c: Cycle, data: CyclesData): string {
  const s = summarize(c);
  const next = data.cycles.find((x) => x.n === c.n + 1);
  const credited = c.changes.filter((x) => x.verdict === 'credited' || x.verdict === 'resolved');
  const missed = c.changes.filter((x) => x.verdict === 'rejected' || x.verdict === 'nolift');
  const drift = c.changes.filter((x) => x.verdict === 'regressed');
  const closed = data.cycles.filter((x) => x.state === 'closed');
  const after = replay(data.day0, closed)[closed.indexOf(c) + 1];
  const out: string[] = [
    `# ${c.id} · ${c.theme}`,
    '',
    `${data.project} · day ${c.openedDay} to day ${c.closedDay ?? '?'} · engine ${c.engine}`,
    '',
    `**${sign(s.net)} rungs.** ${s.credited} credited, ${s.resolved} resolved by a probe, ${s.missed} not earned, ${s.regressed} drift caught. ` +
      `After ${c.id} the project held ${after ? total(after) : '?'} of 36 (day 0: ${total(data.day0)}).`,
    '',
    '| Change | Stage | Move | Verdict | Why |',
    '|---|---|---|---|---|',
    ...c.changes.map(row),
    '',
  ];
  if (credited.length) out.push('## Credited', '', ...credited.map((x) => `- ${ref(x)} ${x.stage} ${rungLabel(x.from)} → R${x.to}: ${x.why}`), '');
  if (missed.length) out.push('## Not earned (carried forward)', '', ...missed.map((x) => `- ${ref(x)} ${x.stage}: ${x.why}`), '');
  if (drift.length) out.push('## Drift caught', '', ...drift.map((x) => `- ${x.stage} fell ${rungLabel(x.from)} → R${x.to}: ${x.why}`), '');
  out.push(
    '## Can this be believed?',
    '',
    data.drift.length ? `- Replay does NOT match the ${data.scannedAt} scan on: ${data.drift.join(', ')}.` : `- Day 0 plus every closed cycle, replayed, equals the ${data.scannedAt} scan.`,
    data.breaks.length ? `- The chain has ${data.breaks.length} break(s): ${data.breaks.map((b) => `${b.cycle} ${b.stage}`).join(', ')}.` : '- The chain holds: every change starts at the rung the replay holds for its stage.',
    `- Credit never crosses engine versions: the whole cycle ran on engine ${c.engine}.`,
    '',
  );
  if (next) {
    out.push(`## Next: ${next.id} · ${next.theme} (${next.state})`, '', ...(next.changes.length ? next.changes.map((x) => `- ${ref(x)} ${x.stage} ${rungLabel(x.from)} → R${x.to}: ${x.title}`) : ['- nothing picked yet']), '');
  }
  out.push('_Generated by Afterlife from the cycle record. Illustrative demo data._');
  return out.join('\n');
}

/** The exact command that posts a report as an issue (the report is written to a file first). */
export const postCommand = (c: Cycle, project: string): string =>
  `glab issue create -R ${project} --title "${reportTitle(c, project)}" --label afterlife::cycle --description "$(cat ${c.id.toLowerCase()}-report.md)"`;
